name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_HOME: /opt/maven
      #DOCKER_REGISTRY: 18.216.88.91:9002
      DOCKER_IMAGE: my-app

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Unit Testing
      run: mvn test

    - name: Functional Testing
      run: mvn verify -DtestSuite=functional

    - name: Performance Testing
      run: mvn verify -DtestSuite=performance
      
    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=Argocd \
          -Dsonar.host.url=http://3.145.203.136:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build Docker Image
      run: docker build -t 18.216.88.91:9002/repository/gitactions/${{ env.DOCKER_IMAGE }}:latest .

    - name: Log in to Nexus
      run: echo ${{ secrets.NEXUS_PASSWORD }} | docker login -u ${{ secrets.NEXUS_USERNAME }} --password-stdin http://18.216.88.91:9002

    # - name: Docker Login & Push to Nexus
    #   # env:
    #   #   NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    #   run: |
    #     docker login 18.216.88.91:9002 -u admin --password admin ||
    #     docker push 18.216.88.91:9002/repository/gitactions/${{ env.DOCKER_IMAGE }}:latest || { echo "Docker push failed"; exit 1; }
