name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_HOME: /opt/maven
      DOCKER_REGISTRY: http://18.118.36.159:8082
      DOCKER_IMAGE: my-app

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Unit Testing
      run: mvn test

    - name: Functional Testing
      run: mvn verify -DtestSuite=functional

    - name: Performance Testing
      run: mvn verify -DtestSuite=performance
      
    - name: SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn sonar:sonar \
          -Dsonar.projectKey=Argocd \
          -Dsonar.host.url=http://3.145.203.136:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Build Docker Image
      run: docker build -t ${{ env.DOCKER_REGISTRY }}/repository/test/${{ env.DOCKER_IMAGE }}:latest .

    - name: Docker Login & Push to Nexus
      # env:
      #   NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        docker login ${{ env.DOCKER_REGISTRY }} -u admin --password admin ||
        docker push ${{ env.DOCKER_REGISTRY }}/repository/test/${{ env.DOCKER_IMAGE }}:latest || { echo "Docker push failed"; exit 1; }
